# Generated by Django 2.1.7 on 2019-03-04 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regaleapp', '0002_auto_20190304_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='area',
            new_name='name',
        ),
    ]
