# Generated by Django 2.1.7 on 2019-03-05 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regaleapp', '0003_auto_20190304_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='is_avaialable',
            new_name='is_available',
        ),
    ]
