# Generated by Django 2.1.7 on 2019-03-08 12:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('regaleapp', '0004_auto_20190305_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='regaleapp.Restaurant'),
            preserve_default=False,
        ),
    ]
