# Generated by Django 2.1.7 on 2019-03-11 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regaleapp', '0006_auto_20190311_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='is_available',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='regaleapp.Location'),
        ),
        migrations.AlterField(
            model_name='person',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='regaleapp.Restaurant'),
        ),
    ]
